### ISSUE TITLE
{"detail":"Not Found"} When trying to access the Web UI

### ISSUE THREAD

**Issue by tehniemer** [hay-kot/mealie#192]
**Describe the bug**
When trying to access the Web UI only an error is shown `{"detail":"Not Found"}`

**Steps To Reproduce**
1. Spin up new container
2. Go to Web UI
3. See error

**Expected behavior**
It works

**Actual Behavior**
See above

**Device Information (please complete the following information):**
 - OS: Debian
 - Deployment: Docker Compose
 - Browser: Chromium Edge
 - Version: latest

**Additional context**
These errors show in the container logs
```
INFO:     192.168.29.99:51330 - "GET / HTTP/1.1" 404 Not Found,
INFO:     192.168.29.99:51330 - "GET /favicon.ico HTTP/1.1" 404 Not Found
```
Compose file:
```
## Mealie - A Self Hosted Recipe Manager.
  mealie:
    image: hkotel/mealie
    container_name: mealie
    restart: unless-stopped
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - '$MEALIE_PORT:9000'
    volumes:
      - '$DOCKER_DIR/mealie:/app/data'
    environment:
      db_type: sqlite
      TZ: $TZ
    labels:
      - 'traefik.enable=true'
      ## HTTP Routers
      - 'traefik.http.routers.mealie-rtr.entrypoints=https'
      - 'traefik.http.routers.mealie-rtr.rule=Host(`mealie.$DOMAINNAME`)'
      ## Middlewares
      - 'traefik.http.routers.mealie-rtr.middlewares=chain-authelia@file' #Authelia Authentication
      ## HTTP Services
      - 'traefik.http.routers.mealie-rtr.service=mealie-svc'
      - 'traefik.http.services.mealie-svc.loadbalancer.server.port=9000'
```
