### ISSUE TITLE
"Copy icon" not working in "sign up links" on raspberry pi (armv7)

### ISSUE THREAD

**Issue by maguilara** [hay-kot/mealie#397]
**Describe the bug**
The quick-copy icon in the sign-up links sections is not working, no content is shared to the clipboard.

**Steps To Reproduce**
Please be specific!
1. Go to settings -> manager users
2. click on "create link" and add link name and proceed to save it.
3. Click on the quick-copy icon of the newly generated link

**Expected behavior**
Copy link to clipboard

**Actual Behavior**
No content is copied to clipboard

**Device Information (please complete the following information):**
 - OS: win10 (client), raspberryos 32bit (server). edit. raspberry pi 4 8gb
 - Deployment: docker-compose
 - Browser: happened first in firefox, tested brave and same thing
 - Version: 0.4.3
docker-compose file:
```
version: "3.1"
services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: unless-stopped
    ports:
      - 9925:80
    environment:
      DB_TYPE: sqlite
      TZ: ${TZ}
    volumes:
      - ${ROOT_DOCKER}/mealie:/app/data
```
TZ, ROOT_DOCKER are environment variable that you can find on the .env file
