### ISSUE TITLE
Upgraded to 0.5.2 everything blank

### ISSUE THREAD

**Issue by sfgrabowski** [hay-kot/mealie#637]
I've just pulled the latest docker image and all my recipes have gone and I am unable to login and receive a "Could Not Validate Credentials" error when logging in. The "changeme" account didn't work either.

Thankfully using docker so rolled back to v0.5.1 and everything has loaded again.

**Comment by 2fst4u** [comment]
I upgraded too but my container won't start, just gives the backing off error.

0.5.1 is ok.

**Comment by wengtad** [comment]
Probably could try to add in some environments.

docker compose:
```yaml
environment:
  PUID: 1000
  PGID: 1000
  TZ: America/Anchorage

  # Gunicorn
  WEB_CONCURRENCY: 2
  # WORKERS_PER_CORE: 0.5
  # MAX_WORKERS: 8
```
[docs](https://hay-kot.github.io/mealie/documentation/getting-started/install/#docker-compose-with-sqlite)
