### ISSUE TITLE
Error when using example docker-compose file

### ISSUE THREAD

**Issue by wtrdk** [hay-kot/mealie#642]
Hi,

When using the example docker-compose file I get this error message:
`"services.mealie.environment.RECIPE_PUBLIC contains true, which is an invalid type, it should be a string, number, or a null"`

My docker-compose file:
```
version: "3.1"
services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: always
    ports:
      - 9925:80
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Amsterdam

      # Default Recipe Settings
      RECIPE_PUBLIC: true
      RECIPE_SHOW_NUTRITION: true
      RECIPE_SHOW_ASSETS: true
      RECIPE_LANDSCAPE_VIEW: true
      RECIPE_DISABLE_COMMENTS: false
      RECIPE_DISABLE_AMOUNT: false

      # Gunicorn
      WEB_CONCURRENCY: 2
      # WORKERS_PER_CORE: 0.5
      # MAX_WORKERS: 8
    volumes:
      - /opt/mealie/data/:/app/data
```

Can anyone help me?
