### ISSUE TITLE
Error importing

### ISSUE THREAD

**Issue by Dulanic** [hay-kot/mealie#7]
I get the following error when I try ti import from a URL. I am using your basic docker-compose.
`
2021-01-03T00:14:14.494770224Z INFO:     192.168.2.202:36156 - "POST /api/recipe/create-url/ HTTP/1.1" 400 Bad Request
`
```
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: redacted  # Change!
      MONGO_INITDB_ROOT_PASSWORD: redacted   # Change!

  mongo-express: # Optional Mongo GUI
    image: mongo-express
    restart: always
    ports:
      - 9091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: redacted
      ME_CONFIG_MONGODB_ADMINPASSWORD: redacted
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: always
    ports:
      - 9002:9000
    environment:
      db_username: redacted     # Your Mongo DB Username - Please Change
      db_password: redacted  # Your Mongo DB Password - Please Change
      db_host: mongo
      db_port: 27017    # The Default port for Mongo DB
    volumes:
      - ./data/img:/app/data/img
      - ./data/backups:/app/data/backups      
```
