### ISSUE TITLE
Can't save recipe

### ISSUE THREAD

**Issue by fabelol** [hay-kot/mealie#9]
Hi,

for testing purposes ive spun this up in a brand new vps. installed Docker and docker-compose. Used your exact docker-compose from the website without changing anything. It doesnt seem to work though. I can't save Recipes. It just gets stuck in the saving animation.

this is the EXACT code i was using, because its on a vps just for testing this. Anything wrong with it?

```
version: "3.1"
services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: always
    ports:
      - 9000:9000
    environment:
      db_username: root     # Your Mongo DB Username - Please Change
      db_password: example  # Your Mongo DB Password - Please Change
      db_host: mongo
      db_port: 27017    # The Default port for Mongo DB
      TZ: America/Anchorage
    volumes:
      - ./data/img:/app/data/img
      - ./data/backups:/app/data/backups

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Change!
      MONGO_INITDB_ROOT_PASSWORD: example   # Change!

  mongo-express: # Optional Mongo GUI
    image: mongo-express
    restart: always
    ports:
      - 9091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
```
